### ISSUE TITLE
Color changed with chrome update

### ISSUE THREAD

**Issue by ttecho** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#127]
After the last chrome update, some of the colors in this theme have become unreadable. Values evaluated in console are a dark purple and almost unreadable. 
![capture](https://cloud.githubusercontent.com/assets/1775183/7252162/58fe8fb8-e800-11e4-9529-9d47066e62e0.PNG)

**Comment by mauricecruz** [comment]
What version are you running? I don't see this problem on Dev or Canary.

**Comment by ttecho** [comment]
Version 43.0.2357/.18 beta-m

**Comment by spectre013** [comment]
running the same version as ttecho and seeing some of the same strangeness in the console.

**Comment by mauricecruz** [comment]
I see. Looks like beta is in an intermediary stage between changes on stable and canary. 

I only certify this theme on stable and canary. Hopefully it'll be resolved in the next beta release.

**Comment by bmakuh** [comment]
This theme is great! However, is there any support planned for DevTools extensions like [React Dev Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en)? Unfortunately it looks like the above screenshot right now.

**Comment by mauricecruz** [comment]
@spectre013 / @ttecho is this still an issue? I see that `stable` bumped up to v.43. 

@bmakuh Thanks! Unfortunately, due to the sandboxing nature of extensions, any css changes I make won't affect other extensions. The reason why React Devtools probably looks messed it up is because they're assuming the devtools background is white and styling with that assumption without explicitly setting their extension background to white.

I can see if I can disable this theme for other extensions. Not sure if I'll have a styling hook for it though.

**Comment by spectre013** [comment]
@mauricecruz No, things are back to normal now. Thank you
