### ISSUE TITLE
React tab is not themed

### ISSUE THREAD

**Issue by underclown** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#134]
I've using your theme for a few months and like it a lot. However, I added the React dev tool extension but the new tab that is added to the dev tools is not themed. Any chance of supporting that?

**Comment by mauricecruz** [comment]
There's no way I can support it through this extension because each extension is sandboxed each other.

But, there's a way you can inject the theme. It's a few steps long and you'll have to run it each time you open devtools. Does the job though.

Here's a link to it: https://gist.github.com/mauricecruz/f53c932961a04c01a096#file-zdm-react-devtools-md

![image](https://cloud.githubusercontent.com/assets/1640686/8371098/315eb036-1ba0-11e5-8757-b44b5423086d.png)

**Comment by underclown** [comment]
Thanks for such a quick response and a solution! It doesn't quite work for me though. The console gets the theme but the React pane does not. I do not see a devtools.html option in the <topframe> dropdown but I do see a React Developer Tools option. Even with that selected though, the pane does not change when I run the script in the console. Any ideas?

**Comment by mauricecruz** [comment]
Hmm.. Make sure the React tab is currently selected before you open another devtools session. That will ensure that `devpanel.html` will be available in the console dropdown.

**Comment by underclown** [comment]
Aha. I did not quite understand that part of the instructions because up until now I did not know you could open a devtools session for a devtools session. Thanks!
