### ISSUE TITLE
[Question] Sublime Text color scheme

### ISSUE THREAD

**Issue by WiBla** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#151]
Hello,

I'm in love with your theme ever since I first used it.
I love it so much that I'm thinking of making a color scheme for Sublime Text (2?/3) that will reproduce it as close as I can, and maybe a complete theme ?

I would like to know if you didn't already started to do something similar and/or if I could use your resources to make it, with credits of course (if I come to publish it.. For the moment I'm just thinking of a personal use).

Best regards.

**Comment by mauricecruz** [comment]
Thanks for your kind words. Really appreciate it!

I somewhat have a zero dark matrix theme for sublimetext. It's not fully implemented and stopped working on it because xml is a pain for me to work with.

https://gist.github.com/mauricecruz/9e0501a34ec1382fb509

If you do improve it, please share it so I can use it!

**Comment by WiBla** [comment]
Hey,

I've edited it to be as close as I could to the devtool. (Work In Progress)
Using the package "ScopeHunter" made it really easy ;)
HTML, CSS and JS supported ATM (I will add other languages and BracketHighlighter support in the near future).
I also recommend labelling this issue "Question".

Here is the source: https://gist.github.com/WiBla/40705f1b1c0f28d302d2
If there is anything you want me to change, tell me :)
